title: Muhammad Abdullah Haroon
logo: /img/WhatsApp Image 2025-05-07 at 3.06.43 PM.jpeg
description: Data Analytics & Business Computing student at Middlesex University Dubai | Python, SQL, Excel, Tableau
theme: jekyll-theme-minimal
