title: Muhammad Abdullah Haroon
logo: /img/headshot_circle.png
description: 19 y/o Data Analytics & Business Computing student at Middlesex University Dubai | Python, SQL, Excel, Tableau | O/A Level IT & Maths
show_downloads: true
theme: jekyll-theme-minimal
