title: Muhammad Abdullah Haroon
logo: /img/cropped_image.png
description: Data Analytics & Business Computing student at Middlesex University Dubai | Python, SQL, Excel, Tableau
theme: jekyll-theme-minimal
